### ISSUE TITLE
[QUESTION] Stress-test of the implementation module

### ISSUE THREAD

**Issue by ThucHoang** [argon/node-apn#258]
Hi argon,

I remember reading an issue where you said that you were able to send up to X push messages each second (the theoretical limit from Apple were 9K/s right?), any chance of telling me/us how you managed or how we should implement this to check how effective our solution is?

**Comment by argon** [comment]
I actually tested this in a rather crude way.

I setup a loop to push 10,000 notifications. After the first was `transmitted` I start a timer, then after the 10,000th `transmitted` event was received I stopped the timer.

https://gist.github.com/argon/e7cfa80fc709c5e6a515

Unfortunately this technique doesn't work for me any more as I get an invalid token error half way through, probably because I'm using the same token repeatedly.

Apple suggest that if you are seeing throughput *lower* than 9k/second then improvements could perhaps be made. I was seeing around 10k/second at the time but the limit is with how node handles TCP connections and I don't think many improvements can be made at this point.

**Comment by ThucHoang** [comment]
I tried something like this once, I think Apple suspends your token for a while depending on the count of messages sent to the same token repeatedly. I was sort of "banned" for like 2 hours after 50 push messages.

Thanks for sharing! It's rather hard to find 9K unique tokens or even 5K just to get through them all :P

**Comment by argon** [comment]
You're right, I think something changed because I used to be able to send a lot of messages to one token. Now there definitely seems to be some kind of throttling. It makes a lot of sense that they have changed this.

My test sandbox account also seemed to be suspended and connections were being reset until I recreated my certificates, so that's worth being aware of.

\A

**Comment by ThucHoang** [comment]
I can't find the thread where you said what you managed to hit, do you know which issue-thread you wrote that in?

**Comment by argon** [comment]
I never formalised my findings, but I mentioned it here: https://github.com/argon/node-apn/issues/154#issuecomment-44612078

**Comment by behrad** [comment]
> https://gist.github.com/argon/e7cfa80fc709c5e6a515

What if we use higher connections/process? e.g. maxConnection=5 for each process? Will we catch `numProc * 5 * 10K` ?

**Comment by argon** [comment]
I don't understand your question

**Comment by behrad** [comment]
You are saying to you've reached around 9k notifications with `maxConnection:1` in your gist. right?
What if we use `>1 maxConnection` ? will APN globally rate limit us?
I'm thinking of spawning 10 worker processes each with `maxConnection: 5`. does it mean I can reach 5*9000*10 notifications/sec?

**Comment by argon** [comment]
That is the main reason `maxConnection` exists, yes. APN doesn't globally rate limit as far as I'm aware. Apple specifically recommends opening more sockets for higher throughput.

**Comment by behrad** [comment]
> Apple specifically recommends opening more sockets for higher throughput.

I've found any `max sockets` on APN callers, So it is practical to use around 20-50 connections :)

Thank you for your great efforts to `node-apn` @argon BTW
