### ISSUE TITLE
Connection options ignored

### ISSUE THREAD

**Issue by ilmente** [argon/node-apn#264]
Hi, I'm trying to use the plugin, but, as I set the options for the connection, they are ignored.
For example, if I set the full path for my custom cert.pem or key.pem, they are ignored and the default values are loaded. It can't find the certificates and search them inside the project root.

**Comment by argon** [comment]
Do you have a small example project which you can share with me, that reliably shows the problem happening?

Someone else what having this issue but I have been unable to reproduce it and they could not share more details with me to so I have no way of fixing it.

If you can give me enough information: 
- example project
- operating system
- node version

So that I can reliably reproduce the problem, then I can actually figure out what is causing it and create a fix. However without more details I can't even know where to begin.

Of course if you want to fix it yourself and send a pull request, that would be appreciated also :)

―A

**Comment by alwhiting** [comment]
I am having this problem too; initializing my connection looks like this:
```javascript
var apnOpts = {
    cert: 'keys/cert.pem',
    key: 'keys/key.pem',
    passphrase: 'passphrase123',
    production: false
};
var apnConnection = new apn.Connection(apnOpts);
// other listeners and stuff
```

I get an error that it can't open the cert.pem file from project root when trying to run the node app (on ubuntu): Error: ENOENT, open 'cert.pem'

If I move my cert files to root and give them the default names it works correctly. I have also tried using absolute paths in the config; that also does not work.

I'm gonna look into this for a few more hours, I'll let you know if I discover the cause.

**Comment by argon** [comment]
I just tested this using the following on ubuntu 14.04:

```js
var apn = require('apn');

var token = "<token>";

var service = new apn.connection();

service.on("completed",         function()    { console.log("Completed!")});
service.on("connected",         function()    { console.log("Connected"); });
service.on('disconnected',      function()    { console.log("Disconnected", arguments); });
service.on('error',             function(err) { console.log("Standard error", err); });
service.on('socketError',       function(err) { console.log("Socket error", err.message); });
service.on('timeout',           function()    { console.log("Timeout"); });
service.on('transmissionError', function(err) { console.log("Transmission Error", err); });

service.on("transmitted", function(notification) {
    console.log("Transmitted");
});

var note = new apn.notification();
    note.badge = 1;

service.pushNotification(note, token);
service.shutdown();
```

I had the certs/keys in a different place to that specified and as expected I got the following error message for an incorrect path.
```
Transmission Error 513
Standard error { [Error: ENOENT, open 'keys/cert.pem'] errno: 34, code: 'ENOENT', path: 'keys/cert.pem' }
Socket error ENOENT, open 'keys/cert.pem'
Completed!
```

I'm not sure what else can be done here...
