### ISSUE TITLE
Error 8 Invalid Token makes no sense - Doesn't happen with Ruby

### ISSUE THREAD

**Issue by freak4pc** [argon/node-apn#301]
Hey, 
I'm getting error 8 when trying to send a notification with node-apn but when trying to use Houston (ruby library) it works fine with no error.

I'm not sure what I'm doing wrong.

When trying with Houston or the Ruby Lib the following works with no errors and I get the notification successfully:

**Command Line:**
`apn push "67d9136173761e220a6ea82207f5d5201fef1501b758ce032a10125fd02fecad00" -c ./apns.pem -m "Test test test"`

**Houston:**
```ruby
require 'houston'

APN = Houston::Client.development
APN.certificate = File.read("apns.pem")

notification = Houston::Notification.new(device: "67d9136173761e220a6ea82207f5d5201fef1501b758ce032a10125fd02fecad00")
notification.alert = "Hello, World!"
notification.badge = 1

APN.push(notification)
```

This is not the situation with node-apn. 
I've tried numerous approaches

- Exporting both key and cert together as a p12/pfx and then adding in options `{pfx: "pfx.p12"}`
- Trying to export each separately as a p12, then converting to PEM using 
```
openssl pkcs12 -clcerts -nokeys -out cert.pem -in cert.p12
openssl pkcs12 -nocerts -out key.pem -in key.p12
openssl rsa -in key.pem -out keynoenc.pem // Decrypt
```
And then adding in options `{cert: "cert.pem", "key": "key.pem"}`
- Trying to use my joined PEM in both `cert` and `key` options

All of these options return an error 8 Invalid Token
```
TRANS ERR
{ encoding: 'utf8',
  payload:
   { messageFrom: 'Caroline',
     aps:
      { badge: 3,
        sound: 'ping.aiff',
        alert: '📧 ✉ You have a new message' } },
  expiry: 1440421884,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom":"Caroline","aps":{"badge":3,"sound":"ping.aiff","alert":"📧 ✉ You have a new message"}}',
  truncateAtWordEnd: false,
  _badge: 3,
  _sound: 'ping.aiff',
  _alert: '📧 ✉ You have a new message' }
{ token: <Buffer 67 d9 13 61 73 76 1e 22 0a 6e a8 22 07 f5 d5 20 1f ef 15 01 b7 58 ce 03 2a 10 12 5f d0 2f ec ad 00> }
8
```

My code looks like this more or less
```javascript
var apn   = require('apn')
var conn  = new apn.Connection({production: false})
var dev   = new apn.Device("67d9136173761e220a6ea82207f5d5201fef1501b758ce032a10125fd02fecad00")

var note  = new apn.Notification()
note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 3;
note.sound = "ping.aiff";
note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
note.payload = {'messageFrom': 'Caroline'};

conn.pushNotification(note, dev)

conn.on('error', error => {
        console.log("ERROR" + error)
      })

conn.on('transmitted', (notification, device) => {
        console.log("TRANS")
        console.log(notification)
        console.log(device)
      })

conn.on('completed', () => {
        console.log("COMPLETED")
      })

conn.on('transmissionError', (errorCode, notification, device) => {
        console.log("TRANS ERR")
        console.log(notification)
        console.log(device)
        console.log(errorCode)
      })
```

Hope maybe you could point me in the right direction. I'm really pulling my hair out here.

Thanks
Shai

**Comment by argon** [comment]
If you are getting any "Error 8" messages that does mean the certificates are being accepted by Apple as the error is sent by their servers, so that's a good start. Unfortunately I have no idea the token from nomad is accepted and the one from node is not. The tokens are identical and the buffer is in the correct format. You're right, it makes no sense. Have you tried on another device?

Could you also try running with DEBUG=apn in your environment and post the logs here?

**Comment by ddoria921** [comment]
I'm also getting this same error. Here is the logs that come back from the apn library with DEBUG=apn. 

``` javascript
  apn Initialising connection +0ms
  apn Loading Credentials +1ms
  apn 1 left to send +4ms
  apn Shutdown pending +1ms
  apn Connection established +321ms
  apn Socket drained +104ms 0
  apn closing connections +149ms
  apn Removing socket from pool +0ms 0
  apn 0 left to send +0ms
  apn 0 left to send +8ms
  apn Notification 0 caused an error: 8 +81ms
  apn Raising error: +2ms 8 { encoding: 'utf8',
  payload: 
   { launchId: 'cd64d37b-86ae-4cd2-92a9-59081f99d107',
     launchType: 'work-order',
     aps: 
      { badge: 0,
        sound: 'ping.aiff',
        alert: 'Testing Jake push notifications' } },
  expiry: 1441044250,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"launchId":"cd64d37b-86ae-4cd2-92a9-59081f99d107","launchType":"work-order","aps":{"badge":0,"sound":"ping.aiff","alert":"Testing Jake push notifications"}}',
  truncateAtWordEnd: true,
  _alert: 'Testing Jake push notifications',
  _sound: 'ping.aiff',
  _badge: 0 } { token: <Buffer 16 45 8c 62 07 2b 39 bb 5c 26 74 25 62 90 eb e2 f1 d9 f5 2f bd e6 fd de 84 39 ac 32 ec c1 ec 4e> }
  apn Buffering 0 notifications for resending +4ms
  apn Socket closed +2ms 0
  apn Removing socket from pool +0ms 0
  apn 0 left to send +1ms
```

**Comment by cwoloszynski** [comment]
I am seeing the same issue.  Anyone have any luck finding out how to resolve this?  I am using "Apple Push Notification Test" OS X app to verify that my token is working.  That application sends the notification without error, but node-pan throws an Error 8 for the same token.

**Comment by argon** [comment]
Please ensure you are using the correct certificates and post the logs from your application with `DEBUG=apn` environment variable set.

**Comment by cwoloszynski** [comment]
Thanks for the quick reply.  I updated the original comment with the output of the DEBUG=apn.  

Since I am getting an error code 8, I am assuming that the certificate is valid, etc.  I am using the sandbox APN servers.  When I use the OS X APN Test app and select the sandbox cert, it works. When I use the production cert/URL, the OS X APN Test app also gives an error.  

I am thinking that perhaps I have somehow managed to set up the system for using the production server when it should be the sandbox server.  But the configuration seems to show using the sandbox cert and 'production:false'

**Comment by argon** [comment]
node-apn will refuse to connect if the certificates do not match the selected server

**Comment by cwoloszynski** [comment]
Ok, so the device token works through other APN solutions using the same certificate and pushes a notification to my device.  So the token is good and the certificate must be good since I can connect to the server.  

Any thoughts on what else might be causing this issue?

**Comment by argon** [comment]
Have you verified the token that is being output in the error matches the token you are sending to?

**Comment by argon** [comment]
Which other APN solutions have you tried?

**Comment by cwoloszynski** [comment]
The token from Apple Push Notification Test OS X app is:

4c1d4d23-7e3f4a2d-583213b7-48ba96f0-5224fcec-736977d5-9f90371e-4b4eeeff

From the error log above, the token is:

4c 1d 4d 23 7e 3f 4a 2d 58 32 13 b7 48 ba 96 f0 52 24 fc ec 73 69 77 d5 9f 90 37 1e 4b 4e ee ff

So, the token used in the successful message matches the errored token from the Apple server error code 8 response.


I am using the app from https://github.com/Zambiorix/Apple-Push-Notification-Test.git

**Comment by cwoloszynski** [comment]
Just looked and it appears that the Apple-Push-Notification-Test code is no longer on github.  I'll repost it shortly.

**Comment by cwoloszynski** [comment]
Reposted the APN test tool from my local copy.  Now at:

https://github.com/cwoloszynski/Apple-Push-Notification-Test

**Comment by argon** [comment]
I can see the original ok. The main thing I notice is that that application is using the original (very old) protocol whereas node-apn uses the latest. Perhaps there's a problem there. I wonder if you could try using an older version of node-apn - 1.3.8 - and see if you get the same error?

**Comment by cwoloszynski** [comment]
Thanks for the support and review of the other tool.  I downgraded to 1.3.8 and still get an error, but a different one.  It looks like this version does keep a connection up.    The APN socket closes immediately.

Does that point to something as the source of my error?  I am beginning to suspect my sandbox certificates since the other app gets them directly out of the OS X keychain and I had to export them manually to get them in place for node-apn.    

I had discounted them since it seemed like the certificate was accepted in the newer version, but perhaps the newer version of node-apn does not see the bad certificate until later in the processing? 


 

debug: send APN to:4C1D4D237E3F4A2D583213B748BA96F05224FCEC736977D59F90371E4B4EEEFF with message:Account cwoloszynski@me.com logged in on device Wojciehowicz
  apn Initialising connection +0ms
  apn Initialising module +1ms
  apn 1 left to send +1ms
  apn Connection established +429ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 0
Disconnected from APNS
  apn Initialising connection +1ms
  apn 1 left to send +0ms
verbose: /Users/charlie/hhmedia-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /Users/charlie/hhmedia-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /Users/charlie/hhmedia-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: attached user to request
debug: In DeviceController.register() with params:{"deviceName":"Wojciehowicz","deviceToken":"4C1D4D237E3F4A2D583213B748BA96F05224FCEC736977D59F90371E4B4EEEFF"}
debug: found or created:{"deviceName":"Wojciehowicz","deviceToken":"4C1D4D237E3F4A2D583213B748BA96F05224FCEC736977D59F90371E4B4EEEFF","user":3,"lastContact":"2015-10-16T13:25:16.188Z","createdAt":"2015-10-14T20:07:10.812Z","updatedAt":"2015-10-16T13:25:16.189Z","id":1}
debug: updates will be:{"deviceName":"Wojciehowicz","user":3,"lastContact":"Fri Oct 16 2015 09:28:13 GMT-0400 (EDT)"}
debug: updated device in list:[{"deviceName":"Wojciehowicz","deviceToken":"4C1D4D237E3F4A2D583213B748BA96F05224FCEC736977D59F90371E4B4EEEFF","user":3,"lastContact":"2015-10-16T13:28:13.518Z","createdAt":"2015-10-14T20:07:10.812Z","updatedAt":"2015-10-16T13:28:13.519Z","id":1}]
verbose: /Users/charlie/hhmedia-backend/api/services/Logger.js:68 [Service.Logger.request() called]
  apn Connection established +920ms
Connected
  apn 1 left to send +0ms
  apn Socket closed +0ms 1
Disconnected from APNS
  apn Initialising connection +1ms
  apn 1 left to send +0ms
  apn Connection established +426ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 2
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +1ms
  apn Connection established +417ms
Connected
  apn 1 left to send +0ms
  apn Socket closed +1ms 3
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +0ms
  apn Connection established +413ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 4
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +1ms
  apn Connection established +445ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +1ms 5
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +0ms
  apn Connection established +416ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 6
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +1ms
  apn Connection established +418ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 7
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +0ms
  apn Connection established +453ms
Connected
  apn 1 left to send +1ms
  apn Socket closed +0ms 8
Disconnected from APNS
  apn Initialising connection +0ms
  apn 1 left to send +1ms

**Comment by argon** [comment]
That definitely looks like a certificate problem. Could you run the following command and post the output?

openssl x509 -text -noout -in <pem filename>

—A

**Comment by cwoloszynski** [comment]
THANK YOU!  Ok, I did this and the certificate is fine, etc, but it is for the WRONG application ID.  

Can I offer to buy you a beer or something?  I owe you a huge thanks!  

Note: for those that follow and have similar issues, PLEASE check the certificate's contents if you have ever had more than one and may be using a different/older certificate.

**Comment by argon** [comment]
Glad to hear you sorted it. I'm thinking about opening up donations for the project so if you do want to donate then let me know.

—A

**Comment by chance-an** [comment]
Ran into the same problem. In my case, the production sever is not enabled and I didn't know. Switching to `production:false` fixes the problem.

If your app is not published and you only deploy to a local device, the production server is likely not enabled. Just use the sandbox one, it still delivers the message to your local device too.

**Comment by ajoslin** [comment]
I had the same problem as @cwoloszynski. Thank you! @argon, where's that donation button?

**Comment by chan71** [comment]
I had the same issue as @cwoloszynski too. And thanks to @argon's `openssl x509 -text -noout -in <cert file path>` I found that the App ID is different in the certificate which was created couple of months back from the one that is used in the App. We have changed the App ID recently as we have moved the App from Apple Developer Enterprise Program to Apple Developer Program.
