### ISSUE TITLE
I receive repeated message

### ISSUE THREAD

**Issue by hzxuzhonghu** [argon/node-apn#331]
when  send same message to multiple deviceTokens, and some tokens are invalid , and the last token
is valid. But I found a bug, one of my device receive the same message twice.

So, I removed all invalid tokens, and send a new message to all other vaild tokens, and this time no one received the message twice.
<ps: I maintain at least 10 connections>

I think this maybe cause by the node-apn, how I can figure it out?

**Comment by argon** [comment]
Can you reproduce this problem every time?

—A

**Comment by hzxuzhonghu** [comment]
Yes， we reproduce it every time in our test environment

 

 

发件人: bounces+848413-bbed-hzxuzhonghu=corp.netease.com@sgmail.github.com [mailto:bounces+848413-bbed-hzxuzhonghu=corp.netease.com@sgmail.github.com] 代表 Andrew Naylor
发送时间: 2015年11月13日 15:17
收件人: argon/node-apn <node-apn@noreply.github.com>
抄送: hzxuzhonghu <hzxuzhonghu@corp.netease.com>
主题: Re: [node-apn] I receive repeated message (#331)

 

Can you reproduce this problem every time?

—A

**Comment by hzxuzhonghu** [comment]
I think this may cause by mutiple connections, an more than 1 of them  handleTransmissionError. This may cause the later apnCachedNotifications pushed more than once

**Comment by hzxuzhonghu** [comment]
In my env, maintain at least 10 connections, could multi-connection and multi transmission error trigger this bug or may caused by apns ?

**Comment by argon** [comment]
Do you maintain the connections manually or does node-apn do it for you? node-apn segregates messages between sockets so it seems unlikely that multiple connections would cause this problem

**Comment by hzxuzhonghu** [comment]
I use node-apn auto maitain  10 connections, and I researched your code in connection.js again and again, and it seems no code could cause this issue. weired, and could it be apns process the valid token after the invalid one ? In addition, i use the development sandbox

**Comment by Edwardsj** [comment]
It seems also happen to me.  I copy the demo code and send a message, but got the same message twice.

**Comment by Edwardsj** [comment]
er.... It's only happened when I used in express. So this bug may caused by express or any other things.

**Comment by hzxuzhonghu** [comment]
@Edwardsj Can you guarantee your upper application call node-apn pushNotification only once? If only once, then our issue maybe the same.

**Comment by Edwardsj** [comment]
@hzxuzhonghu  I'm sure about call node-apn pushNotification only once.   I try <a href="https://github.com/logicalparadox/apnagent">apnagent <a> but it still happened .

**Comment by Edwardsj** [comment]
@hzxuzhonghu Add I try php code ,it happened any way, so it seems like some thing wrong in client. we take the wrong way to fix this bug.

**Comment by argon** [comment]
Sorry for not getting back to you sooner. I forgot to mention that you should try enabling the environment variable `DEBUG=apn` which will output extra logging. If you can trigger this problem and post the log I may be able to help further. This is a strange problem I haven't seen before though.

**Comment by didbarbosa** [comment]
Just to let you know I was facing this issue once too.
In sandbox mode, I had an ios device registered with 2 valid tokens. Don't know how it is possible but when looping through all my tokens, this device received the notification twice.
It was not a node-apn issue.

**Comment by weglinski** [comment]
Hi,

I still have the same issue. While sending push messages to multiple device using service.pushNotification(note, tokens) sometimes messages comes twice (or even more) to the same device.

Should I try to use loop sending instead of multiple?

Here are logs:
`apn Option [passphrase] set to null. This may cause unexpected behaviour. +0ms
  apn Initialising connection +5ms
  apn Loading Credentials +0ms
  apn 15 left to send +1ms
POST /api/conference/193/news/ 200 200.506 ms - 141
  apn Connection established +599ms
Connected
  apn Socket drained +104ms 0
Notification transmitted to:db697bb21338c58a3393009679cc602df86bea73996c0911f0a1f0c137ae0b51
  apn 14 left to send +0ms
  apn Socket drained +1ms 0
Notification transmitted to:f1b0abfc52d5b8c56ee5f4b396a65c879c3d8789391255caac8dcaf27dcf7c48
  apn 13 left to send +1ms
  apn Socket drained +0ms 0
Notification transmitted to:112eb17e515333681141db25a22da667b13372f2485afe19d134c8d420af513d
  apn 12 left to send +0ms
  apn Socket drained +1ms 0
Notification transmitted to:00eb1e7bebd751cc48d6cc8e39613d64cf2df9c6279bde9fb10fb95e321b09ba
  apn 11 left to send +1ms
  apn Socket drained +0ms 0
Notification transmitted to:e28365b2ecf810dea295f63b7c8101b21fbfe5ca0672a6c60176cc072963cdd3
  apn 10 left to send +0ms
  apn Clearing notification 0 from the cache +1ms
  apn Socket drained +0ms 0
Notification transmitted to:7746865370e3c02ca4c77b9d4cc3d0198ce520b176ab2a862585c9246f6fcb70
  apn 9 left to send +1ms
  apn Clearing notification 1 from the cache +0ms
  apn Socket drained +0ms 0
Notification transmitted to:abc5d4bf7ac520735415ccbe15c0e814ebdbbbc9b303354cada5a5aa9ec0d23f
  apn 8 left to send +0ms
  apn Clearing notification 2 from the cache +1ms
  apn Socket drained +0ms 0
Notification transmitted to:e74d3a36b57165f17eaa56206669f96d5215dbb04e15bb9dcda881b391fe133f
  apn 7 left to send +0ms
  apn Clearing notification 3 from the cache +0ms
  apn Socket drained +1ms 0
Notification transmitted to:5251d6aec4840689ae593afaf33de67f71dc5da244e766a6382275103a59eca7
  apn 6 left to send +0ms
  apn Clearing notification 4 from the cache +0ms
  apn Socket drained +0ms 0
Notification transmitted to:800da6da2a5169bbc6f24f652a5d05239270c95f1b9f756ce1ba7eadb0ccfbb9
  apn 5 left to send +0ms
  apn Clearing notification 5 from the cache +1ms
  apn Socket drained +0ms 0
Notification transmitted to:722ae010e9136424d5dd0aea19ad2af89196bfbc92581562c6fdedab2276b29d
  apn 4 left to send +0ms
  apn Clearing notification 6 from the cache +0ms
  apn Socket drained +1ms 0
Notification transmitted to:9eab7e1ebc1949b28d691b2c2bb7cc1797b40102e53bda1f93a7cda3bd254c71
  apn 3 left to send +0ms
  apn Clearing notification 7 from the cache +1ms
  apn Socket drained +1ms 0
Notification transmitted to:c0a8f23d8c606713eea93ea81deeece354fcf5a8e5c73c76d742c5a0b4466224
  apn 2 left to send +0ms
  apn Clearing notification 8 from the cache +1ms
  apn Socket drained +0ms 0
Notification transmitted to:596bdc016644ee485a958c081d898a0b3c83dc3b20b12ae48d0adc5e0b19f69f
  apn 1 left to send +0ms
  apn Clearing notification 9 from the cache +1ms
  apn Socket drained +0ms 0
Notification transmitted to:b7d7fd739aa0c7556f10d80dc7f19ce6939f7a5ae22a1591409093f27afc774f
  apn 0 left to send +0ms
  apn 0 left to send +1ms
  apn Notification 1 caused an error: 8 +124ms
A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox
  apn Raising error: +0ms 8 null undefined
APN Error: 8
  apn Buffering 5 notifications for resending +0ms
  apn Socket closed +1ms 0
  apn Removing socket from pool +0ms 0
  apn Initialising connection +0ms
Disconnected from APNS
  apn 5 left to send +0ms
Notification caused error: 8 for device  undefined null
  apn Connection established +413ms
Connected
  apn Socket drained +101ms 1
Notification transmitted to:722ae010e9136424d5dd0aea19ad2af89196bfbc92581562c6fdedab2276b29d
  apn 4 left to send +2ms
  apn Socket drained +2ms 1
Notification transmitted to:9eab7e1ebc1949b28d691b2c2bb7cc1797b40102e53bda1f93a7cda3bd254c71
  apn 3 left to send +0ms
  apn Socket drained +1ms 1
Notification transmitted to:c0a8f23d8c606713eea93ea81deeece354fcf5a8e5c73c76d742c5a0b4466224
  apn 2 left to send +0ms
  apn Socket drained +0ms 1
Notification transmitted to:596bdc016644ee485a958c081d898a0b3c83dc3b20b12ae48d0adc5e0b19f69f
  apn 1 left to send +0ms
  apn Socket drained +0ms 1
Notification transmitted to:b7d7fd739aa0c7556f10d80dc7f19ce6939f7a5ae22a1591409093f27afc774f
  apn 0 left to send +0ms
  apn 0 left to send +1ms
  apn Notification 1 caused an error: 8 +300ms
A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox
  apn Raising error: +3ms 8 { encoding: 'utf8',
  payload: 
   { 'messageFrom ': 'rMeetSender',
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'Some message',
        'url-args': undefined,
        category: undefined } },
  expiry: 1461336243,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom ":"rMeetSender","aps":{"badge":1,"sound":"ping.aiff","alert":"Some message"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'ping.aiff',
  _alert: 'Some message' } Device {
  token: <Buffer 9e ab 7e 1e bc 19 49 b2 8d 69 1b 2c 2b b7 cc 17 97 b4 01 02 e5 3b da 1f 93 a7 cd a3 bd 25 4c 71> }
APN Error: 8
  apn Buffering 3 notifications for resending +1ms
  apn Socket closed +1ms 1
  apn Removing socket from pool +0ms 1
  apn Initialising connection +0ms
Disconnected from APNS
  apn 3 left to send +1ms
Notification caused error: 8 for device  Device {
  token: <Buffer 9e ab 7e 1e bc 19 49 b2 8d 69 1b 2c 2b b7 cc 17 97 b4 01 02 e5 3b da 1f 93 a7 cd a3 bd 25 4c 71> } { encoding: 'utf8',
  payload: 
   { 'messageFrom ': 'rMeetSender',
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'Some message',
        'url-args': undefined,
        category: undefined } },
  expiry: 1461336243,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom ":"rMeetSender","aps":{"badge":1,"sound":"ping.aiff","alert":"Some message"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'ping.aiff',
  _alert: 'Some message' }
  apn Connection established +416ms
Connected
  apn Socket drained +100ms 2
Notification transmitted to:c0a8f23d8c606713eea93ea81deeece354fcf5a8e5c73c76d742c5a0b4466224
  apn 2 left to send +1ms
  apn Socket drained +0ms 2
Notification transmitted to:596bdc016644ee485a958c081d898a0b3c83dc3b20b12ae48d0adc5e0b19f69f
  apn 1 left to send +0ms
  apn Socket drained +1ms 2
Notification transmitted to:b7d7fd739aa0c7556f10d80dc7f19ce6939f7a5ae22a1591409093f27afc774f
  apn 0 left to send +1ms
  apn 0 left to send +0ms
  apn Notification 1 caused an error: 8 +299ms
A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox
  apn Raising error: +1ms 8 { encoding: 'utf8',
  payload: 
   { 'messageFrom ': 'rMeetSender',
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'Some message',
        'url-args': undefined,
        category: undefined } },
  expiry: 1461336243,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom ":"rMeetSender","aps":{"badge":1,"sound":"ping.aiff","alert":"Some message"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'ping.aiff',
  _alert: 'Some message' } Device {
  token: <Buffer 59 6b dc 01 66 44 ee 48 5a 95 8c 08 1d 89 8a 0b 3c 83 dc 3b 20 b1 2a e4 8d 0a dc 5e 0b 19 f6 9f> }
APN Error: 8
  apn Buffering 1 notifications for resending +0ms
  apn Socket closed +1ms 2
  apn Removing socket from pool +0ms 2
  apn Initialising connection +0ms
Disconnected from APNS
  apn 1 left to send +0ms
Notification caused error: 8 for device  Device {
  token: <Buffer 59 6b dc 01 66 44 ee 48 5a 95 8c 08 1d 89 8a 0b 3c 83 dc 3b 20 b1 2a e4 8d 0a dc 5e 0b 19 f6 9f> } { encoding: 'utf8',
  payload: 
   { 'messageFrom ': 'rMeetSender',
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'Some message',
        'url-args': undefined,
        category: undefined } },
  expiry: 1461336243,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom ":"rMeetSender","aps":{"badge":1,"sound":"ping.aiff","alert":"Some message"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'ping.aiff',
  _alert: 'Some message' }
  apn Connection established +417ms
Connected
  apn Socket drained +102ms 3
Notification transmitted to:b7d7fd739aa0c7556f10d80dc7f19ce6939f7a5ae22a1591409093f27afc774f
  apn 0 left to send +1ms
  apn 0 left to send +1ms`

**Comment by MohitJarial** [comment]
Hi , 
I have also the same problem While sending push messages to multiple device using service.pushNotification(note, tokens) sometimes messages come twice (or even more) to the same device.
can anybody help me out of this?

**Comment by oliversalzburg** [comment]
Well, are you listing the same token multiple times? Did you at all debug what is happening?
