### ISSUE TITLE
How to handle the errors

### ISSUE THREAD

**Issue by Ajido** [argon/node-apn#333]
Hi, I have a question about error handling.

I've terminated processes if "error" events occurred. And it is restarted by the upstart, most of the problems were corrected. But those processes had continued to fail without being terminated by "transmissionError" with the code 515.

This problem was fixed by restarting manually, but because I wanted to prevent the recurrence, I modified the code to terminate those processes even when a transmissionError with 515 occurs.

In this case, the above workaround is OK? If there is a better way, please tell me.
I think fatal error should be emitted in the "error" event.

**Comment by silentjohnny** [comment]
I'm having the same problem. It would be nice if after failed connection retries the module would emit an 'error' event and not just transmission errors. Listening to 514 transmissionErrors means acting on multiple (possibly thousands) of error events, which is obviously not what you want. Listening to a socketError is also not what you want, because the module might still retry the socket connection.

Isn't there an 

```javascript
this.emit('error', error) 
```

missing in the module after 

```javascript
this.rejectBuffer(Errors.connectionRetryLimitExceeded);
```

@argon, Can you explain why an error event is thrown in case of wrong environment but not after failed retries?

**Comment by argon** [comment]
In addition to being a fatal error, an incorrect environment can guarantee that no notifications have been sent. In the case of a connection timeout it's possible that some notifications were already sent before the connectivity problems started. Because of this it's important that the `transmissionError` is raised for each notification so that the application can track which notifications were not sent - something many systems are keen to do.

In the case that the retry limit is exceeded it is probably a good idea to emit an error also. I will consider this in future.
