### ISSUE TITLE
retransmit 

### ISSUE THREAD

**Issue by magicdawn** [argon/node-apn#420]
https://github.com/argon/node-apn/blob/master/doc/connection.markdown#event-transmitted

> A notification may also be "transmitted" several times if a preceding notification caused an error requiring retransmission.

- Why retransmit a notification that already successfully transmitted before ?
- if this really needs, why the readme suggests to establish only 1 connection per process to send notifications, that an error will cause all notification retransmitted. One connection per notification sounds like better.

## background

for I'm using mysql as queue to send apn, and use a `status` field to record status, and add a `transmitted` listener to update the status, and I found this listener hook calls more than once. 
That's hard to control and figure out when to update the db.

**Comment by argon** [comment]
`transmitted` indicates that it was sent to Apple i.e. written to the socket. Not that Apple successfully processed the notification.

Apple do not provide positive confirmation when a notification is successfully processed, only when an error occurs. As soon as an error occurs any notifications sent after the one which caused the error will be ignored.

Example:
```
Send: Notification 1
Send: Notification 2
Send: Notification 3
Send: Notification 4
Receive: Error(Notification 3)
Connection closed by Apple
====
Reopen connection
Send: Notification 4
Send: Notification 5
...
```

After each "Send" the module will emit `transmitted`. When the error is received we know that notification 3 caused a problem and an error will be emitted for it. In addition because the module knows that notification 4 was originally sent after 3 (which had an error) then notification 4 was _not_ processed so it must be sent again.

**Comment by magicdawn** [comment]
> After each "Send" the module will emit transmitted. When the error is received we know that notification 3 caused a problem and an error will be emitted for it. In addition because the module knows that notification 4 was originally sent after 3 (which had an error) then notification 4 was not processed so it must be sent again.

That's saying a new connection will shooting the error and connections don't bother each other, right ?
