### ISSUE TITLE
Can you add feature for error code with 410, which specifies device token is no longer active for the topic

### ISSUE THREAD

**Issue by anuragtiwari890** [argon/node-apn#425]
Hi Argon, 
              While reading on APNs from devloper.apple.com, i got to know that we can get information about expired device token there itself by the error code 410. This will avoid implementing feedback service. [The APNs link from where i read.](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW1)
             I have also found an [stackoverflow article](http://stackoverflow.com/questions/34630585/does-apns-feedback-service-no-longer-exist-as-per-new-apis)  which says apple may deprecate the feedback service in future. 
             It would be helpful if our connection can emit an error for "DeviceTokenExpired". Lastly sorry for the issue created, but more than an issue it can be considered as a feature.

**Comment by argon** [comment]
This is dependent on supporting the new protocol and is implemented in #278

**Comment by veera06** [comment]
Hello Argon,

Need some help/clarification about HTTP2 provider, I went to HTTP2 documentation and see there is  410 status code if the device token is no longer active for the topic." 

1).I install the app and I am able send push using new HTTP2 dev provider 
2). Uninstall the app and tried send push to same device token 
3). Still getting 200 status code instead of 410
Can you please help on this

**Comment by trobriander** [comment]
@veera06, I'm having the same issue. This happens with sandbox APNs server. Perhaps it is only implemented with live APNs server?

**Comment by greatvovan** [comment]
@veera06, @trobriander The same is in production APNs.
